
language: php

git:
    depth: 5

php:
    - 7.1
    - 7.2
    - 7.3

install:
    - travis_retry composer clear-cache
    - travis_retry composer self-update
    - travis_retry composer install

script:
    - vendor/bin/tale-dev check --report --coverage-php-version=7.1

addons:
    code_climate:
        repo_token: 926e4ef30bd5a4f43893e175304d0416ac343ff0b95963be76e015a6abc7d7c8
